# Generated by Django 5.2.1 on 2025-07-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="invoice",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
        migrations.AddField(
            model_name="expense",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
    ]
